"""add category to custom_shopping_item

Revision ID: 1c60bd4b6697
Revises: 9fb6a840846a
Create Date: 2026-04-07 21:13:26.930237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c60bd4b6697'
down_revision = '9fb6a840846a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_shopping_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), server_default='Miscellaneous', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_shopping_item', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
