"""add hidden to tag

Revision ID: 851d6f856c9b
Revises: 1c60bd4b6697
Create Date: 2026-04-07 21:23:48.154031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851d6f856c9b'
down_revision = '1c60bd4b6697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_column('hidden')

    # ### end Alembic commands ###
