"""add instructions, parsed ingredients, fiber_g_target

Revision ID: e568a698458d
Revises: 
Create Date: 2026-04-07 18:21:33.018401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e568a698458d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diet_goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fiber_g_target', sa.Float(), nullable=True))

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_url', sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column('nutrition_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('instructions')
        batch_op.drop_column('nutrition_source')
        batch_op.drop_column('source_url')

    with op.batch_alter_table('diet_goal', schema=None) as batch_op:
        batch_op.drop_column('fiber_g_target')

    # ### end Alembic commands ###
